#!/bin/sh
ssh -T -i SportifyKey.pem ubuntu@172.31.23.80 <<EOF
    cd ~/FinalCloudProject-ReactJS
    git pull origin master
    git reset --hard
    npm install
    echo "Preparing for prod build"
    echo `hostname`
    npm run build | tee /home/ubuntu/deploy.logs
    echo "Deploy Logs are stored on the server at path /home/ubuntu/deploy.logs"
    echo "build is deployed with symbolic links to nginx web server, reloading nginx"
    sudo systemctl reload nginx
    sudo systemctl status nginx
    exit
EOF
